In [4]:
!pip install pandas
!pip install numpy

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\ayush\anaconda3\envs\surprise\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ayush\anaconda3\envs\surprise\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ayush\anaconda3\envs\surprise\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.3 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.3 MB 5.0 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.3 MB 6.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.3 MB 5.9 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 5.9 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 7.0 MB/s  0:00:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.3
Requirement already satisfied: numpy in c:\users\ayush\anaconda3\envs\surprise\lib\site-packages (1.26.4)

In [5]:
import numpy as np
import pandas as pd

In [6]:
ratings = pd.read_csv("ratings.csv")

In [7]:
ratings.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [8]:
movies = pd.read_csv("movies.csv")

In [9]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [10]:
ratings["userId"].unique().shape[0]

7120

In [11]:
ratings["movieId"].unique().shape[0]

14026

In [12]:
print(f'numbers of users = {ratings["userId"].unique().shape[0]} AND number of movies = {ratings["movieId"].unique().shape[0]}')

numbers of users = 7120 AND number of movies = 14026

In [13]:
Ratings = ratings.pivot(index = 'userId', columns ='movieId', values = 'rating').fillna(0)
Ratings.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,129350,129354,129428,129707,130052,130073,130219,130462,130490,130642
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
!pip install scikit-surprise

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-surprise
  Using cached scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

WARNING: Ignoring invalid distribution ~umpy (C:\Users\ayush\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/scikit-surprise/
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Compiling surprise/similarities.pyx because it changed.
      Compiling surprise/prediction_algorithms/matrix_factorization.pyx because it changed.
      Compiling surprise/prediction_algorithms/optimize_baselines.pyx because it changed.
      Compiling surprise/prediction_algorithms/slope_one.pyx because it changed.
      Compiling surprise/prediction_algorithms/co_clustering.pyx because it changed.
      [1/5] Cythonizing surprise/prediction_algorithms/co_clustering.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.avg_cltr_i = avg_cltr_i
              self.avg_cocltr = avg_cocltr

              return self

          def compute_averages(self, np.ndarray[np.int_t] cltr_u,
                                                   ^
      ------------------------------------------------------------
      surprise\prediction_algorithms\co_clustering.pyx:157:45: Invalid type.
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ayush\AppData\Local\Temp\pip-build-env-dssew2pt\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ayush\AppData\Local\Temp\pip-build-env-dssew2pt\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\ayush\AppData\Local\Temp\pip-build-env-dssew2pt\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 116, in <module>
        File "C:\Users\ayush\AppData\Local\Temp\pip-build-env-dssew2pt\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1153, in cythonize
          cythonize_one(*args)
          ~~~~~~~~~~~~~^^^^^^^
        File "C:\Users\ayush\AppData\Local\Temp\pip-build-env-dssew2pt\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1297, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: surprise/prediction_algorithms/co_clustering.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution ~umpy (C:\Users\ayush\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\ayush\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\ayush\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [16]:
from surprise import Reader , Dataset,SVD
from surprise.model_selection import cross_validate

reader = Reader()

data = Dataset.load_from_df(ratings[["userId","movieId","rating"]],reader)

svd = SVD()

cross_validate(svd,data,measures=['RMSE','MAE'],cv=3,verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    0.8440  0.8455  0.8460  0.8452  0.0008
MAE (testset)     0.6469  0.6480  0.6478  0.6476  0.0005
Fit time          5.21    5.12    5.15    5.16    0.03
Test time         1.80    1.75    1.63    1.73    0.07

{'test_rmse': array([0.84403525, 0.84549435, 0.84603632]),
 'test_mae': array([0.64686518, 0.64801771, 0.6478071 ]),
 'fit_time': (5.206403017044067, 5.124540567398071, 5.1490161418914795),
 'test_time': (1.7999982833862305, 1.7524511814117432, 1.632596492767334)}

In [20]:
ratings_1 = ratings[(ratings['userId'] == 1) & (ratings['rating'] == 5)]
ratings_1 = ratings_1.set_index('movieId')
ratings_1 = ratings_1.join(movies) ['title']
ratings_1.head(10)

movieId
4993           Honky Tonk Freeway (1981)
5952        Harder They Come, The (1973)
7153                Dreamers, The (2003)
8507    Barkleys of Broadway, The (1949)
Name: title, dtype: object

In [22]:
user_1 = movies.copy()

user_1 = user_1.reset_index()

# getting full dataset
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)

trainset = data.build_full_trainset()

svd.fit(trainset)

user_1['Estimate_Score'] = user_1['movieId'].apply(lambda x: svd.predict(1, x).est)
user_1 = user_1.drop(['movieId','genres','index'], axis = 1)

user_1 = user_1.sort_values('Estimate_Score', ascending=False)
print(user_1.head(10))

                                                   title  Estimate_Score
7041   Lord of the Rings: The Return of the King, The...        4.670133
4897   Lord of the Rings: The Fellowship of the Ring,...        4.617828
8937                     Decalogue, The (Dekalog) (1989)        4.605741
5853       Lord of the Rings: The Two Towers, The (2002)        4.594995
6901                     Night of the Hunter, The (1955)        4.593395
3003                                      Matewan (1987)        4.592991
18990                                Black Mirror (2011)        4.541047
6172           Day for Night (La Nuit Américaine) (1973)        4.539812
10923              Devil and Daniel Johnston, The (2005)        4.535167
1049                             Murder, My Sweet (1944)        4.533190